@Validators.API_HostAddress = http://localhost:5157

POST {{Validators.API_HostAddress}}/cnpj/validator
Content-Type: application/json
{
    "value": "12.ABC.345/01DE-35"
}
###

POST {{Validators.API_HostAddress}}/cnpj/validator
Content-Type: application/json
{
    "value": "12ABC34501DE35"
}
###

POST {{Validators.API_HostAddress}}/cnpj/validator
Content-Type: application/json
{
    "value": "56.ABC.345/21DE-70"
}
###

POST {{Validators.API_HostAddress}}/cnpj/validator
Content-Type: application/json
{
    "value": "18.781.203/0001-28"
}
###

POST {{Validators.API_HostAddress}}/cnpj/validator
Content-Type: application/json
{
    "value": "1"
}
###

POST {{Validators.API_HostAddress}}/cnpj/validator
Content-Type: application/json
{
    "value": "123456789123456789"
}
###
